import type { Course } from './catalog';

export const mockCourses: Course[] = [
  {
    slug: 'sell-on-instagram',
    title: 'Sell on Instagram',
    type: 'workshop',
    description: 'Turn your everyday product into a clear, confident Instagram offer people can act on.',
    instructor: 'Neema Mushi',
    instructorRole: 'Digital commerce coach',
    duration: '3h 20m',
    level: 'Starter',
    price: 45000,
    rating: 4.9,
    students: 284,
    image: 'coral',
    mark: '01',
    sections: [
      { title: 'Make your offer clear', lessons: [{ title: 'What are you really selling?', duration: '18 min', freePreview: true }, { title: 'Your simple product promise', duration: '24 min', freePreview: false }] },
      { title: 'Build a page that sells', lessons: [{ title: 'Profile, bio and highlights', duration: '31 min', freePreview: true }, { title: 'A week of posts in one sitting', duration: '42 min', freePreview: false }] },
      { title: 'Turn attention into action', lessons: [{ title: 'DM conversations that convert', duration: '36 min', freePreview: false }, { title: 'Your first 10-day plan', duration: '29 min', freePreview: false }] },
    ],
  },
  {
    slug: 'ai-for-real-work',
    title: 'AI for Real Work',
    type: 'ai',
    description: 'A practical first course in using AI to write, plan and think faster without losing your voice.',
    instructor: 'Baraka Sanga',
    instructorRole: 'Product builder and AI educator',
    duration: '4h 10m',
    level: 'Starter',
    price: 60000,
    rating: 4.8,
    students: 417,
    image: 'teal',
    mark: 'AI',
    sections: [
      { title: 'A useful mental model', lessons: [{ title: 'AI without the hype', duration: '16 min', freePreview: true }, { title: 'The prompt that gets you moving', duration: '28 min', freePreview: true }] },
      { title: 'Build your working toolkit', lessons: [{ title: 'Research and summarise in minutes', duration: '36 min', freePreview: false }, { title: 'Write a better first draft', duration: '31 min', freePreview: false }] },
      { title: 'Make it part of your week', lessons: [{ title: 'A repeatable AI workflow', duration: '41 min', freePreview: false }, { title: 'Your practical next experiment', duration: '25 min', freePreview: false }] },
    ],
  },
  {
    slug: 'phone-photography',
    title: 'Phone Photography',
    type: 'workshop',
    description: 'See better light, frame with intention and make images that give your small brand a point of view.',
    instructor: 'Amani Joseph',
    instructorRole: 'Photographer and visual storyteller',
    duration: '2h 45m',
    level: 'Starter',
    price: 35000,
    rating: 4.7,
    students: 193,
    image: 'gold',
    mark: '02',
    sections: [
      { title: 'See the light', lessons: [{ title: 'The window light test', duration: '22 min', freePreview: true }, { title: 'Colour, shade and mood', duration: '29 min', freePreview: false }] },
      { title: 'Frame the story', lessons: [{ title: 'Three reliable compositions', duration: '34 min', freePreview: false }, { title: 'Photographing people with ease', duration: '38 min', freePreview: false }] },
    ],
  },
  {
    slug: 'design-with-canva',
    title: 'Design with Canva',
    type: 'workshop',
    description: 'Make clean, memorable flyers and social posts from a blank canvas — no design degree required.',
    instructor: 'Rehema Kweka',
    instructorRole: 'Brand designer',
    duration: '3h 05m',
    level: 'Starter',
    price: 40000,
    rating: 4.8,
    students: 328,
    image: 'ink',
    mark: '03',
    sections: [
      { title: 'The visual basics', lessons: [{ title: 'Good design in plain language', duration: '25 min', freePreview: true }, { title: 'Type and colour that work', duration: '32 min', freePreview: false }] },
      { title: 'Your first design system', lessons: [{ title: 'Build a reusable template', duration: '39 min', freePreview: false }, { title: 'Create a campaign set', duration: '45 min', freePreview: false }] },
    ],
  },
  {
    slug: 'no-code-website-weekend',
    title: 'Your First Website',
    type: 'workshop',
    description: 'Go from idea to a polished, shareable website over one focused weekend.',
    instructor: 'Jabali Omari',
    instructorRole: 'No-code maker',
    duration: '5h 15m',
    level: 'Intermediate',
    price: 75000,
    rating: 4.9,
    students: 146,
    image: 'code',
    mark: '04',
    sections: [
      { title: 'Plan before you build', lessons: [{ title: 'A page people understand', duration: '21 min', freePreview: true }, { title: 'Content that does the job', duration: '35 min', freePreview: false }] },
      { title: 'Build and launch', lessons: [{ title: 'Your first responsive page', duration: '62 min', freePreview: false }, { title: 'Polish, test and publish', duration: '48 min', freePreview: false }] },
    ],
  },
  {
    slug: 'ai-for-content-creators',
    title: 'AI for Content Creators',
    type: 'ai',
    description: 'Find your ideas faster, develop a voice and create a month of useful content with a lighter lift.',
    instructor: 'Baraka Sanga',
    instructorRole: 'Product builder and AI educator',
    duration: '3h 50m',
    level: 'Intermediate',
    price: 65000,
    rating: 4.8,
    students: 231,
    image: 'teal',
    mark: 'AI',
    sections: [
      { title: 'Start with your point of view', lessons: [{ title: 'The content compass', duration: '23 min', freePreview: true }, { title: 'Prompting in your own voice', duration: '34 min', freePreview: false }] },
      { title: 'Plan a month in an hour', lessons: [{ title: 'From raw idea to useful post', duration: '39 min', freePreview: false }, { title: 'Edit like a human', duration: '31 min', freePreview: false }] },
    ],
  },
];
